"""Session watcher module for Claude Session Player."""

from __future__ import annotations

from claude_session_player.watcher.api import WatcherAPI
from claude_session_player.watcher.config import (
    BotConfig,
    ConfigManager,
    IndexConfig,
    SearchConfig,
    SessionConfig,
    SessionDestinations,
    SlackDestination,
    TelegramDestination,
    apply_env_overrides,
    expand_paths,
    migrate_config,
)
from claude_session_player.watcher.search_db import IndexedSession, SearchDatabase
from claude_session_player.watcher.debouncer import MessageDebouncer, PendingUpdate
from claude_session_player.watcher.deps import check_slack_available, check_telegram_available
from claude_session_player.watcher.destinations import AttachedDestination, DestinationManager
from claude_session_player.watcher.event_buffer import EventBuffer, EventBufferManager
from claude_session_player.watcher.file_watcher import FileWatcher, IncrementalReader
from claude_session_player.watcher.message_state import (
    MessageAction,
    MessageStateTracker,
    NoAction,
    SendNewMessage,
    SessionMessageState,
    TurnState,
    UpdateExistingMessage,
)
from claude_session_player.watcher.service import WatcherService
from claude_session_player.watcher.sse import SSEConnection, SSEManager
from claude_session_player.watcher.state import SessionState, StateManager
from claude_session_player.watcher.slack_publisher import (
    SlackAuthError,
    SlackError,
    SlackPublisher,
    ToolCallInfo as SlackToolCallInfo,
    escape_mrkdwn,
    format_context_compacted_blocks,
    format_system_message_blocks,
    format_turn_message_blocks,
    format_user_message_blocks,
    get_tool_icon as slack_get_tool_icon,
)
from claude_session_player.watcher.telegram_bot import (
    BotCommandDef,
    TelegramBotConfig,
    TelegramBotState,
    TelegramPollingRunner,
    build_webhook_url,
    delete_telegram_webhook,
    get_bot_info,
    get_webhook_info,
    initialize_telegram_bot,
    setup_telegram_webhook,
    shutdown_telegram_bot,
    start_telegram_polling,
)
from claude_session_player.watcher.telegram_publisher import (
    TelegramAuthError,
    TelegramError,
    TelegramPublisher,
    ToolCallInfo,
    escape_markdown,
    format_context_compacted,
    format_system_message,
    format_turn_message,
    format_user_message,
    get_tool_icon,
)
from claude_session_player.watcher.transformer import transform

__all__ = [
    "apply_env_overrides",
    "AttachedDestination",
    "BotCommandDef",
    "BotConfig",
    "build_webhook_url",
    "check_slack_available",
    "check_telegram_available",
    "ConfigManager",
    "expand_paths",
    "IndexConfig",
    "IndexedSession",
    "migrate_config",
    "delete_telegram_webhook",
    "DestinationManager",
    "MessageDebouncer",
    "PendingUpdate",
    "escape_markdown",
    "escape_mrkdwn",
    "EventBuffer",
    "EventBufferManager",
    "FileWatcher",
    "format_context_compacted",
    "format_context_compacted_blocks",
    "format_system_message",
    "format_system_message_blocks",
    "format_turn_message",
    "format_turn_message_blocks",
    "format_user_message",
    "format_user_message_blocks",
    "get_bot_info",
    "get_tool_icon",
    "get_webhook_info",
    "initialize_telegram_bot",
    "IncrementalReader",
    "MessageAction",
    "MessageStateTracker",
    "NoAction",
    "SearchConfig",
    "SendNewMessage",
    "SessionConfig",
    "SessionDestinations",
    "SessionMessageState",
    "SessionState",
    "setup_telegram_webhook",
    "shutdown_telegram_bot",
    "SlackAuthError",
    "SlackDestination",
    "SlackError",
    "SlackPublisher",
    "SlackToolCallInfo",
    "slack_get_tool_icon",
    "SSEConnection",
    "SSEManager",
    "start_telegram_polling",
    "StateManager",
    "TelegramAuthError",
    "TelegramBotConfig",
    "TelegramBotState",
    "TelegramDestination",
    "TelegramError",
    "TelegramPollingRunner",
    "TelegramPublisher",
    "ToolCallInfo",
    "TurnState",
    "UpdateExistingMessage",
    "SearchDatabase",
    "WatcherAPI",
    "WatcherService",
    "transform",
]
